// crack-lore-injector / ui-copy 모듈
// 역할: 초심자용 한국어 UI 문구 중앙 관리
(function () {
  'use strict';

  const _w = (typeof unsafeWindow !== 'undefined') ? unsafeWindow : window;
  _w.__LoreInjCopy = _w.__LoreInjCopy || {};
  if (_w.__LoreInjCopy.__copyLoaded) return;

  const labels = {
    menuTitle: '설정 정보',
    mainSettings: '기본 설정',
    quickSettings: '빠른 설정',

    enabledTitle: '설정 정보 자동 삽입',
    enabledDesc: '대화에 필요한 설정 자동 삽입.',

    compressionTitle: '자동 압축',
    compressionDesc: '입력 공간 부족하면 설정 문장 자동 압축.',
    compressionMode: '압축 방식',

    searchSection: '검색과 감지',
    embeddingSearchTitle: '의미 기반 검색',
    embeddingSearchDesc: '단어가 달라도 비슷한 설정 찾음.',
    embeddingModel: '의미 검색 모델',
    autoEmbeddingTitle: '검색 데이터 자동 갱신',
    autoEmbeddingDesc: '대화에서 설정 찾은 뒤 검색 데이터 갱신.',
    decayTitle: '오래된 설정 다시 확인',
    decayDesc: '오래 안 나온 설정도 필요하면 다시 넣음.',
    rerankTitle: '검색 결과 다시 고르기',
    rerankDesc: 'AI가 검색 결과 한 번 더 골라 정확도 높임.',

    insertPositionTitle: '삽입 위치',
    insertPositionDesc: '내 메시지 기준 설정 넣을 위치.',
    insertBefore: '메시지 앞',
    insertAfter: '메시지 뒤',

    extraInfoSection: '추가 정보',
    honorificTitle: '호칭 정보',
    honorificDesc: '등장인물 사이 호칭 짧게 정리해서 전달.',
    continuityTitle: '관계 흐름 확인',
    continuityDesc: '처음 만남, 재회, 호칭 변화 같은 흐름 함께 확인.',

    outputFormat: '삽입 문장 형식',
    resetSettings: '모든 설정 초기화 (저장된 설정 묶음은 유지)',
    presetApplyConfirm: '프리셋 적용?',
    settingsRefreshNeeded: '새로고침 필요함.',
    settingsRefreshTitle: '설정 갱신 필요',
    modelChangedRegenNeeded: '모델 변경됨. 기존 검색 데이터 재생성 필요.',
    resetSettingsConfirm: '설정 초기화?',
    versionCountSuffix: '개 버전 (최신순)',
    restoreAction: '복원',
    closeAction: '닫기',
    saveAction: '저장',
    restoreVersionConfirm: '이 버전으로 복원? 현재 상태 자동 백업됨.',
    restoreDone: '복원됨.',
    jsonErrorPrefix: 'JSON 오류',
    errorPrefix: '오류',
    typeMismatchPrefix: '타입 불일치',
    typeLabelPrefix: '타입',
    anchorToggleFailed: '고정 변경 실패',
    editDone: '수정됨.',
    deleteEntryConfirm: '삭제?',
    mergeGroupLabel: '그룹',
    similarityLabel: '유사도',
    anchoredLabel: '고정됨',
    summaryMissing: '(요약 없음)',
    previewGenerating: '생성 중',
    chunkLabel: '청크',
    failedChunkLabel: '실패',
    userInputLabel: '입력',
    injectedLabel: '삽입',
    sceneLabel: '장면',
    firstEncounterLabel: '첫 만남',
    reunionLabel: '재회',
    honorificLabel: '호칭',
    settingLabel: '설정',
    bundleLabel: '묶음',
    skippedLabel: '건너뜀',
    totalLabel: '전체',
    charUnit: '자',
    manualRefinePhaseFindTarget: '대상 탐색',
    manualRefinePhaseCollectSettings: '설정 수집',
    manualRefinePhaseCollectMemory: '기억 수집',
    manualRefinePhaseCallAi: 'AI 확인 중',
    manualRefinePhaseApply: '반영 중',

    refinerTitle: '응답 교정',
    refinerEnableTitle: '응답 교정 켜기',
    refinerEnableDesc: 'AI 응답이 저장된 설정과 어긋나는지 확인.',
    refinerAutoApplyTitle: '자동 적용',
    refinerAutoApplyDesc: '확인 창 없이 교정 결과 바로 적용.',
    honorificSensitivity: '호칭 교정 민감도',

    loreListMenu: '설정 목록',
    loreMergeMenu: '중복 설정 정리',
    snapshotMenu: '백업 관리',
    fileMenu: '파일 관리',
    extractMenu: '대화 정리',
    logMenu: '실행 기록',
    sessionMenu: '세션 상태',

    activePackEmpty: '활성화된 파일 없음. 파일 관리에서 사용할 파일 켜기.',
    activeEntryEmpty: '사용할 수 있는 항목 없음.',
    loreListPanelTitle: '설정 목록 관리',
    loadingText: '불러오는 중',
    versionHistoryUnavailable: '버전 이력 기능 불러오기 실패. 페이지 새로고침 필요.',
    noVersionHistory: '저장된 버전 없음. 다음 변경부터 기록됨.',

    embeddingAction: '검색 데이터',
    embeddingProcessing: '생성 중',
    embeddingReady: '검색 준비됨',
    embeddingNeedsRegen: '다시 생성 필요',
    embeddingChanged: '내용 변경됨',
    embeddingMissing: '검색 데이터 없음',
    copyAction: '복사',
    editAction: '수정',
    deleteAction: '삭제',
    historyAction: '이력',
    anchorOn: '고정됨',
    anchorOff: '고정',
    anchorOnTitle: '고정 해제.',
    anchorOffTitle: '자동 정리 중 덮어쓰지 않게 고정.',
    doneText: '완료',
    failedText: '실패',
    copyDone: '복사됨.',
    copyFailed: '복사 실패.',

    fileImportTitle: '설정 파일 가져오기',
    loreNamePlaceholder: '파일 이름',
    importJsonFile: 'JSON 파일 가져오기',
    manualJsonInput: '또는 JSON 직접 입력',
    manualJsonPlaceholder: '[{"name":"이름","triggers":["키워드"],"type":"character","summary":"설명","detail":{}}]',
    manualAddAction: '직접 추가',
    defaultManualPackName: '직접 추가',
    jsonRequired: 'JSON 입력 필요.',
    importDone: '항목 처리 완료',
    newItemCount: '새 항목',
    importFailed: '가져오기 실패.',
    jsonParseFailed: 'JSON 확인 필요.',
    registeredPackEmpty: '등록된 파일 없음.',
    exportAction: '내보내기',
    itemEmpty: '항목 없음.',
    packEmbeddingConfirm: '검색 데이터 생성?',
    embeddingApiKeyRequired: '검색 데이터 생성용 API 키 필요.',
    apiSettingRequired: 'API 설정 필요.',

    loreMergePanelTitle: '중복 설정 정리',
    mergeTitle: '중복 설정 병합',
    mergeDesc: '검색 데이터 유사도로 중복 후보를 찾고, 그룹별로 직접 확인한 뒤 병합. 핵심 정보 보존, 글자수 상한, 타입 경고 적용.',
    mergeScopeNote: '현재 페이지에서 켠 파일 항목만 대상. 다른 페이지나 꺼진 파일은 건드리지 않음.',
    mergeThresholdLabel: '유사도 기준',
    mergeMaxCharsLabel: '최대 글자수',
    mergeFindCandidates: '병합 후보 찾기',
    mergeSearching: '검색 중',
    mergeTooFewActive: '활성 항목 2개 미만.',
    mergeTooFewEmbeddings: '검색 데이터 있는 항목 2개 미만. 파일 관리에서 검색 데이터 먼저 생성 필요.',
    mergeGroupsFound: '후보 그룹 발견.',
    mergeNoCandidates: '기준 이상 후보 없음.',
    mergeBulkMode: '일괄 모드',
    mergeBulkPlaceholder: '모든 그룹에 적용할 방식 선택',
    mergeKeepLongest: '가장 긴 항목 유지 + 키워드 합치기',
    mergeLlmSummarize: 'AI 요약 병합',
    mergeUndo: '직전 병합 취소',
    mergeUndoConfirm: '직전 병합 취소하고 원본 항목 복원?',
    mergeRestored: '복원 완료.',
    mergeNoGroups: '후보 없음. 기준을 낮춰 재시도 가능.',
    mergeTypeRiskTitle: '타입 다를 때 영향',
    mergeTypeRiskDesc: '주제별 분류가 흐려질 수 있음. 키워드가 뒤섞이면 관련 없는 상황에서 항목이 들어갈 수 있음. 병합 후 한쪽 타입으로 고정되므로 필요한 경우에만 진행.',
    mergePreview: '미리보기',
    mergeRun: '병합 실행',
    mergePreviewTitle: '병합 미리보기',
    mergeApplyingOverLimit: 'summary가 글자수 상한 초과. 그래도 적용?',
    mergeTypeMismatchConfirm: '타입이 다름. 주제 경계가 무너질 수 있음. 계속?',
    mergeConfirm: '개 항목을 하나로 병합? 되돌리기 지원.',
    mergeEmbeddingDone: '검색 데이터 재생성 완료.',
    mergeEmbeddingManualNeeded: 'API 미설정 — 파일 관리에서 수동 생성 필요.',
    mergeEmbeddingFailed: '검색 데이터 재생성 실패.',
    mergeComplete: '병합 완료.',

    extractPanelTitle: '대화 정리 설정',
    autoExtractTitle: '자동 대화 정리',
    autoExtractDesc: '대화를 일정 주기마다 읽고 설정 항목으로 저장.',
    includeDbTitle: '기존 설정 함께 확인',
    includeDbDesc: '이미 저장된 JSON을 함께 보내 중복 저장 줄임.',
    includePersonaTitle: '캐릭터 이름 함께 확인',
    includePersonaDesc: '대화 정리 때 캐릭터 이름도 함께 보내 정확도 높임.',
    extractTurnsLabel: '주기',
    extractRangeLabel: '범위',
    extractOffsetLabel: '오프셋',
    extractPackNameLabel: '저장 파일 이름',
    selectExistingPack: '기존 파일 선택',
    manualExtractRun: '수동 정리 실행',
    manualExtractConfirm: '수동 정리 시작?',
    batchExtractTitle: '전체 대화 일괄 정리',
    batchExtractDesc: '긴 기존 대화를 나눠 한 번에 정리. API 비용 큼 — 초기 이동용.',
    batchTurnsLabel: '배치 크기',
    batchOverlapLabel: '겹침',
    batchRetryLabel: '재시도',
    batchExtractRun: '전체 일괄 정리 실행',
    batchExtractConfirm: '전체 대화를 배치로 나눠 분석. API 비용 큼. 계속?',
    batchRunning: '실행 중',
    batchLoadingLogs: '전체 대화 가져오는 중',
    batchProcessing: '배치 처리 중',
    batchDone: '완료',
    batchFailedDetail: '실패 상세는 로그 탭',
    templateManagerTitle: '프롬프트 템플릿 관리',
    newTemplateAction: '새 템플릿',
    schemaJsonLabel: '스키마 (JSON)',
    promptWithoutDbLabel: '프롬프트 (기존 설정 미포함)',
    promptWithDbLabel: '프롬프트 (기존 설정 포함)',

    logPanelTitle: '실행 기록',
    logResetAction: '초기화',
    logDeleteConfirm: '기록 삭제?',
    logEmpty: '기록 없음.',
    logInjectionTitle: '삽입 기록',
    logExtractionTitle: '정리 기록',
    logRefinerTitle: '교정 기록',
    logContradictionTitle: '모순 기록',
    logDetailsLabel: '내역',
    logOptimizeLabel: '최적화',
    logBudgetLabel: '예산',
    logNoMatch: '매치 없음',

    sessionPanelTitle: '세션 상태 관리',
    sessionTitle: '현재 세션 상태',
    sessionClearAll: '세션 전체 초기화',
    sessionClearConfirm: '이 채팅방의 쿨다운, 시간감쇠 점수, 턴 수 모두 초기화?',
    sessionNoActiveEntries: '현재 켜진 설정 없음.',

    snapshotPanelTitle: '백업 관리',
    snapshotRestoreTitle: '백업 복원',
    snapshotEmpty: '저장된 백업 없음.',
    snapshotRestoreConfirm: '이 시점으로 복원? 기존 데이터 덮어씀.',
    snapshotRestoreDone: '복원 완료.',
    snapshotDeleteConfirm: '백업 삭제?',

    refinerPanelTitle: '응답 교정 설정',
    refinerMissing: '응답 교정 모듈 없음.',
    manualRefineTitle: '수동 검수',
    manualRefineDesc: '마지막 AI 응답 즉시 다시 확인. 이미 처리된 응답도 다시 실행 가능.',
    recentRefineAction: '최근 AI 응답 다시 확인',
    refinerUpdateNeeded: '응답 교정 모듈 버전 낮음. 스크립트 수동 업데이트 필요.',
    chatDetectFailed: '채팅방 감지 실패.',
    manualRefineRunning: '검수 실행 중',
    manualRefineNoTarget: '마지막 AI 응답 없음',
    refinerModeTitle: '설정 검색 방식',
    refinerModeKeyword: '키워드 매칭만',
    refinerModeSemantic: '의미 검색',
    refinerTemplateSelect: '검수 템플릿 선택',
    refinerCustomPromptOption: '직접 입력',
    refinerDynamicPromptOption: '주제별 선택',
    refinerTopicHeader: '검수 주제 선택 — 체크한 항목만 AI에게 요청',
    refinerLogicGroup: '모순 검수',
    refinerRepairGroup: '끊김 복구',
    refinerContextTurns: '참조 대화 턴 수',
    refinerPromptLabel: '프롬프트',
    refinerDynamicDesc: '아래 체크박스로 검수 주제 켜고 끔. 체크한 항목만 프롬프트에 들어감.',
    refinerCustomDesc: '직접 작성한 프롬프트 사용.',
    refinerClearQueue: '처리 기록 초기화',
    refinerQueueCleared: '기록 삭제됨.',

    templateRenameAction: '이름 변경',
    templateResetAction: '초기화',
    templateNewNamePrompt: '새 템플릿 이름:',
    templateRenamePrompt: '템플릿 이름:',
    templateDefaultReadonly: '기본 템플릿 수정 불가 — 초기화 불필요.',
    templateResetConfirm: '템플릿을 기본 내용으로 초기화?',
    templateResetDone: '초기화 완료.',
    templateDeleteConfirm: '템플릿 삭제?',

    convertTitle: '지식 변환 (URL/텍스트 → 설정)',
    convertUrlPlaceholder: 'URL 입력',
    convertPackPlaceholder: '파일 이름',
    convertUrlAction: 'URL 변환',
    convertTextTitle: '텍스트 → 설정 파일',
    convertTextPlaceholder: '설정, 세계관, 캐릭터 설명 등',
    convertTextAction: '텍스트 변환',
    convertMissingUrlPack: 'URL과 파일 이름 필요.',
    convertMissingTextPack: '텍스트와 파일 이름 필요.',
    convertRunning: '변환 중',
    convertCreatedSuffix: '개 생성',
    convertNoExtractable: '추출 가능한 내용 없음.'
  };

  const presets = {
    beginner: {
      name: '기본 추천',
      desc: '의미 기반 검색과 자동 정리 함께 사용.'
    },
    minimal: {
      name: '가볍게 사용',
      desc: '자동 정리는 끄고 필요할 때만 직접 실행.'
    },
    advanced: {
      name: '정밀 모드',
      desc: '검색 결과 한 번 더 고르고 응답 교정까지 사용.'
    }
  };

  const help = {
    embeddingSearch: [
      '단어가 정확히 같지 않아도 비슷한 설정 찾음.',
      '예: “왕궁 정원” 입력해도 “궁전의 뒤뜰” 설정 찾을 수 있음.'
    ].join('\n'),
    cooldown: [
      '최근에 넣은 설정은 잠시 쉬게 해서 같은 문장 반복 방지.',
      '예: 6으로 설정하면 약 6번의 대화 동안 같은 설정 다시 안 넣음.'
    ].join('\n'),
    honorificSensitivity: [
      '낮음: 명백한 오류만 수정',
      '보통: 맥락상 어색한 경우 제안',
      '높음: 저장된 호칭과 다르면 적극 확인'
    ].join('\n')
  };

  _w.__LoreInjCopy = {
    labels,
    presets,
    help,
    __copyLoaded: true
  };


})();